version: "3"

services:
  db:
    container_name: db
    image: postgres:16-alpine
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    container_name: api
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgresVolume: